# Generated by Django 2.0.7 on 2019-08-08 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('month', models.DateField(verbose_name='mês')),
                ('file', models.FileField(upload_to='sales_imported_files', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='arquivo')),
                ('status', models.CharField(choices=[('PROCESSING', 'Em processamento'), ('IMPORTED', 'Importado com sucesso'), ('ERROR', 'Falha ao importar os dados, verifique o arquivo e envie-o novamente!')], default='PROCESSING', max_length=15, verbose_name='status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário que enviou')),
            ],
            options={
                'verbose_name': 'arquivo Importado',
                'verbose_name_plural': 'arquivos Importados',
            },
        ),
    ]
